[package]
name = "sinix-desktop"
version = "0.1.0"
description = "Sinix Desktop"
authors = [ "Sanket Chaudhari" ]
license = "MIT"
repository = "https://github.com/sinix-dev/sinix"
default-run = "sinix"
edition = "2018"
build = "src/build.rs"

[dependencies]
serde_json = "1.0"
sinix = { git = "https://github.com/sinix-dev/sinix-rs" }
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "0.9", features = [ "all-api" ] }

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "sinix"
path = "src/main.rs"
