[package]
name = "sinix"
version = "0.1.0"
description = "A Sandbox Game"
authors = [ "Sanket Chaudhari" ]
license = "MIT"
repository = "https://github.com/sanket143/sinix"
default-run = "sinix"
edition = "2018"
build = "src/build.rs"

[dependencies]
ws = "0.9"
warp = "0.2"
serde_json = "1.0"
env_logger = "0.7"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "0.9", features = [ "all-api" ] }
uuid = { version = "0.4", features = [ "serde", "v4" ] }
futures = { version = "0.3", default-features = false }
tokio = { version = "0.2", features = [ "macros", "sync" ] }

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
embedded-server = [ "tauri/embedded-server" ]
no-server = [ "tauri/no-server" ]

[[bin]]
name = "sinix"
path = "src/main.rs"
